create table if not exists public.lr_documents (
  id text primary key,
  name text not null,
  size_bytes bigint not null default 0,
  chunk_count integer not null default 0,
  status text not null default 'ready',
  uploaded_at timestamptz not null default now(),
  storage_path text,
  public_url text,
  error_message text
);

create index if not exists lr_documents_uploaded_at_idx
  on public.lr_documents (uploaded_at desc);

create table if not exists public.lr_chat_messages (
  id bigint generated by default as identity primary key,
  user_id text,
  document_id text,
  session_id text,
  document_name text,
  question text not null,
  answer text not null,
  language text not null default 'en',
  sources jsonb not null default '[]'::jsonb,
  confidence double precision not null default 0,
  latency_ms integer not null default 0,
  model_used text not null default '',
  sufficient_evidence boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists lr_chat_messages_user_id_idx
  on public.lr_chat_messages (user_id);

create index if not exists lr_chat_messages_document_id_idx
  on public.lr_chat_messages (document_id);

create index if not exists lr_chat_messages_session_id_idx
  on public.lr_chat_messages (session_id);

create index if not exists lr_chat_messages_created_at_idx
  on public.lr_chat_messages (created_at desc);

alter table public.lr_chat_messages
  add column if not exists user_id text,
  add column if not exists document_name text,
  add column if not exists question text,
  add column if not exists answer text,
  add column if not exists language text not null default 'en',
  add column if not exists sources jsonb not null default '[]'::jsonb,
  add column if not exists confidence double precision not null default 0,
  add column if not exists latency_ms integer not null default 0,
  add column if not exists model_used text not null default '',
  add column if not exists sufficient_evidence boolean not null default true;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'lr_chat_messages'
      and column_name = 'content'
  ) then
    execute $sql$
      update public.lr_chat_messages
      set
        question = coalesce(question, content, ''),
        answer = coalesce(answer, ''),
        language = coalesce(language, 'en'),
        sources = coalesce(sources, '[]'::jsonb),
        confidence = coalesce(confidence, 0),
        latency_ms = coalesce(latency_ms, 0),
        model_used = coalesce(model_used, ''),
        sufficient_evidence = coalesce(sufficient_evidence, true)
      where
        question is null
        or answer is null
        or language is null
        or sources is null
        or confidence is null
        or latency_ms is null
        or model_used is null
        or sufficient_evidence is null
    $sql$;
  else
    update public.lr_chat_messages
    set
      question = coalesce(question, ''),
      answer = coalesce(answer, ''),
      language = coalesce(language, 'en'),
      sources = coalesce(sources, '[]'::jsonb),
      confidence = coalesce(confidence, 0),
      latency_ms = coalesce(latency_ms, 0),
      model_used = coalesce(model_used, ''),
      sufficient_evidence = coalesce(sufficient_evidence, true)
    where
      question is null
      or answer is null
      or language is null
      or sources is null
      or confidence is null
      or latency_ms is null
      or model_used is null
      or sufficient_evidence is null;
  end if;
end $$;
