"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _chat_empty_state from './chat-empty-state.bones.json'
import _results_metrics from './results-metrics.bones.json'
import _benchmark_dashboard from './benchmark-dashboard.bones.json'
import _eval_simplify_demo from './eval-simplify-demo.bones.json'
import _profile_page from './profile-page.bones.json'

configureBoneyard({"color":"#ece8df","darkColor":"#26241d","animate":"shimmer","shimmerColor":"#f4f1ea","darkShimmerColor":"#31302a","speed":"2s","shimmerAngle":110})

registerBones({
  "chat-empty-state": _chat_empty_state,
  "results-metrics": _results_metrics,
  "benchmark-dashboard": _benchmark_dashboard,
  "eval-simplify-demo": _eval_simplify_demo,
  "profile-page": _profile_page,
})
