import { getShare } from "@/lib/api"
import { ChatMarkdown } from "@/components/chat-panel/chat-markdown"
import { notFound } from "next/navigation"
import Link from "next/link"
import Image from "next/image"
import type { Metadata } from "next"
import { ArrowRight, ArrowLeft, BookOpen, ShieldCheck } from "lucide-react"
import { plainExcerpt } from "./share-text"
import logo from "@/public/icons/android-chrome-512x512.png"
import { ScrollArea } from "@/components/ui/scroll-area"
import { ShareSources } from "./share-sources"

type SharePageProps = { params: Promise<{ slug: string }> }

export async function generateMetadata({
  params,
}: SharePageProps): Promise<Metadata> {
  const { slug } = await params
  const data = await getShare(slug)
  if (!data) return { title: "Shared answer" }

  const title = plainExcerpt(data.question, 70)
  const description = plainExcerpt(data.answer, 160)
  const docName = data.sources?.[0]?.doc_name?.replace(/\.pdf$/i, "") ?? ""
  const fullDescription = docName ? `${description} — ${docName}` : description
  const locale = data.language?.startsWith("ms")
    ? "ms_MY"
    : data.language?.startsWith("zh")
      ? "zh_CN"
      : "en_US"
  return {
    title,
    description: fullDescription,
    openGraph: {
      title: `${title} – Lingua Rakyat`,
      description: fullDescription,
      type: "article",
      url: `/share/${slug}`,
      locale,
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} – Lingua Rakyat`,
      description: fullDescription,
    },
  }
}

const COPY = {
  ms: {
    kicker: "Jawapan Dikongsi",
    q: "S",
    sources: "Sumber",
    ask: "Tanya Soalan Anda Sendiri",
    back: "Kembali ke Lingua Rakyat",
    disclaimer:
      "Jawapan ini dijana oleh Lingua Rakyat. Sentiasa sahkan dengan sumber rasmi kerajaan.",
    confidence: { high: "Padanan tinggi", medium: "Padanan sederhana", low: "Sila sahkan" },
  },
  en: {
    kicker: "Shared Answer",
    q: "Q",
    sources: "Sources",
    ask: "Ask Your Own Question",
    back: "Back to Lingua Rakyat",
    disclaimer:
      "This answer was generated by Lingua Rakyat. Always verify with official government sources.",
    confidence: { high: "High match", medium: "Medium match", low: "Verify this one" },
  },
  zh: {
    kicker: "分享的回答",
    q: "问",
    sources: "来源",
    ask: "提出您自己的问题",
    back: "返回 Lingua Rakyat",
    disclaimer: "此回答由 Lingua Rakyat 生成。请务必以官方政府来源为准核实。",
    confidence: { high: "匹配度高", medium: "匹配度中", low: "请核实" },
  },
}

function copyFor(language?: string) {
  if (language?.startsWith("zh")) return COPY.zh
  if (language?.startsWith("ms") || language?.startsWith("id")) return COPY.ms
  return COPY.en
}

function ConfidenceBadge({
  label,
  text,
}: {
  label: string
  text: string
}) {
  const isHigh = label === "high"
  return (
    <span
      className={
        isHigh
          ? "inline-flex items-center gap-1 rounded-full bg-success/10 px-2.5 py-0.5 text-xs font-medium text-success"
          : "inline-flex items-center gap-1 rounded-full bg-warning/10 px-2.5 py-0.5 text-xs font-medium text-warning"
      }
    >
      <ShieldCheck className="h-3 w-3" />
      {text}
    </span>
  )
}

function formatDate(iso: string, language?: string) {
  try {
    return new Date(iso).toLocaleDateString(
      language?.startsWith("ms") ? "ms-MY" : language?.startsWith("zh") ? "zh-CN" : "en-US",
      { day: "numeric", month: "short", year: "numeric" }
    )
  } catch {
    return ""
  }
}

export default async function SharePage({ params }: SharePageProps) {
  const { slug } = await params
  const data = await getShare(slug)
  if (!data) notFound()

  const copy = copyFor(data.language)
  const confidenceText =
    copy.confidence[(data.confidence_label as "high" | "medium" | "low") ?? "medium"] ??
    copy.confidence.medium

  return (
    <div className="relative flex min-h-dvh flex-col items-center px-4 py-6 sm:py-12">
      <div className="flex w-full max-w-2xl flex-col">
        {/* Header */}
        <div className="mb-6 flex shrink-0 items-center justify-between sm:mb-8">
          <Link href="/" className="flex items-center gap-2.5">
            <Image
              src={logo}
              alt="Lingua Rakyat"
              width={28}
              height={28}
              className="rounded-full object-cover"
            />
            <span className="font-heading text-xs font-semibold tracking-[0.3em] text-foreground uppercase">
              Lingua Rakyat
            </span>
          </Link>
          <Link
            href="/"
            className="hidden items-center gap-1.5 text-xs font-medium text-muted-foreground transition-colors hover:text-primary sm:flex"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            {copy.back}
          </Link>
        </div>

        {/* Card */}
        <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
          {/* Top section: metadata */}
          <div className="border-b border-border px-5 py-4 sm:px-8 sm:py-5">
            <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
              <span className="text-xs font-semibold tracking-[0.25em] text-primary uppercase">
                {copy.kicker}
              </span>
              {data.agency ? (
                <span className="rounded-full bg-primary/10 px-2.5 py-0.5 text-xs font-medium text-primary">
                  {data.agency}
                </span>
              ) : null}
              {data.confidence_label ? (
                <ConfidenceBadge label={data.confidence_label} text={confidenceText} />
              ) : null}
              {data.created_at ? (
                <span className="ml-auto text-xs text-muted-foreground">
                  {formatDate(data.created_at, data.language)}
                </span>
              ) : null}
            </div>
          </div>

          {/* Question */}
          <div className="border-b border-border bg-muted/30 px-5 py-4 sm:px-8 sm:py-5">
            <p className="font-heading text-base font-semibold leading-relaxed text-foreground sm:text-lg">
              <span className="mr-2 text-primary">{copy.q}:</span>
              {data.question}
            </p>
          </div>

          {/* Answer + sources (scrollable if long) */}
          <ScrollArea className="max-h-[60vh]">
            <div className="px-5 py-5 sm:px-8 sm:py-6">
              <div className="prose prose-sm max-w-none text-foreground prose-headings:font-heading prose-headings:text-foreground prose-a:text-primary prose-strong:text-foreground">
                <ChatMarkdown content={data.answer} />
              </div>

              {data.sources.length > 0 && (
                <div className="mt-8 border-t border-border pt-5">
                  <div className="mb-3 flex items-center gap-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
                    <BookOpen className="h-3.5 w-3.5" />
                    {copy.sources}
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    <ShareSources sources={data.sources} />
                  </div>
                </div>
              )}
            </div>
          </ScrollArea>
        </div>

        {/* CTA + disclaimer */}
        <div className="mt-6 sm:mt-8">
          <Link
            href="/workspace"
            className="group flex items-center justify-center gap-2 rounded-full bg-primary px-6 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm transition-all hover:bg-primary/90 hover:shadow-md sm:py-3"
          >
            {copy.ask}
            <ArrowRight className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
          </Link>

          <p className="mt-3 text-center text-xs leading-relaxed text-muted-foreground sm:mt-4">
            {copy.disclaimer}
          </p>
        </div>
      </div>
    </div>
  )
}
