import { getShare } from "@/lib/api"
import { ChatMarkdown } from "@/components/chat-panel/chat-markdown"
import { notFound } from "next/navigation"

export default async function SharePage({ params }: { params: { slug: string } }) {
  const data = await getShare(params.slug)
  if (!data) notFound()

  return (
    <div className="mx-auto max-w-2xl px-4 py-12">
      <div className="mb-2 text-xs font-semibold uppercase tracking-widest text-muted-foreground">
        Lingua Rakyat · Shared answer
      </div>

      <div className="mb-6 rounded-lg border border-border bg-muted/30 px-4 py-3 text-sm text-foreground">
        <span className="font-medium">Q: </span>{data.question}
      </div>

      <div className="prose prose-sm max-w-none dark:prose-invert">
        <ChatMarkdown content={data.answer} />
      </div>

      {data.sources.length > 0 && (
        <div className="mt-6 border-t border-border pt-4">
          <div className="mb-2 text-xs font-semibold text-muted-foreground">Sources</div>
          {data.sources.map((s, i) => (
            <div key={i} className="mb-1 text-xs text-muted-foreground">
              {s.doc_name || s.document_id}{s.page_start ? ` · p.${s.page_start}` : ""}
            </div>
          ))}
        </div>
      )}

      <div className="mt-8 text-center text-xs text-muted-foreground">
        This answer was generated by{" "}
        <a href="/" className="text-primary underline">Lingua Rakyat</a>.
        Always verify with official government sources.
      </div>
    </div>
  )
}
