import { getShare } from "@/lib/api"
import { ChatMarkdown } from "@/components/chat-panel/chat-markdown"
import { notFound } from "next/navigation"
import Link from "next/link"
import Image from "next/image"
import type { Metadata } from "next"
import { ArrowRight, ArrowLeft, BookOpen, ShieldCheck } from "lucide-react"
import { plainExcerpt } from "./share-text"
import logo from "@/public/icons/android-chrome-512x512.png"
import bgNew from "@/public/assets/background-new3.png"
import bgMobile from "@/public/assets/bg-mobile.png"
import { ScrollArea } from "@/components/ui/scroll-area"

type SharePageProps = { params: Promise<{ slug: string }> }

export async function generateMetadata({
  params,
}: SharePageProps): Promise<Metadata> {
  const { slug } = await params
  const data = await getShare(slug)
  if (!data) return { title: "Shared answer" }

  const title = plainExcerpt(data.question, 70)
  const description = plainExcerpt(data.answer, 160)
  const docName = data.sources?.[0]?.doc_name?.replace(/\.pdf$/i, "") ?? ""
  const fullDescription = docName ? `${description} — ${docName}` : description
  const locale = data.language?.startsWith("ms")
    ? "ms_MY"
    : data.language?.startsWith("zh")
      ? "zh_CN"
      : "en_US"
  return {
    title,
    description: fullDescription,
    openGraph: {
      title: `${title} – Lingua Rakyat`,
      description: fullDescription,
      type: "article",
      url: `/share/${slug}`,
      locale,
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} – Lingua Rakyat`,
      description: fullDescription,
    },
  }
}

const COPY = {
  ms: {
    kicker: "Jawapan Dikongsi",
    q: "S",
    sources: "Sumber",
    ask: "Tanya Soalan Anda Sendiri",
    back: "Kembali ke Lingua Rakyat",
    disclaimer:
      "Jawapan ini dijana oleh Lingua Rakyat. Sentiasa sahkan dengan sumber rasmi kerajaan.",
    confidence: { high: "Padanan tinggi", medium: "Padanan sederhana", low: "Sila sahkan" },
  },
  en: {
    kicker: "Shared Answer",
    q: "Q",
    sources: "Sources",
    ask: "Ask Your Own Question",
    back: "Back to Lingua Rakyat",
    disclaimer:
      "This answer was generated by Lingua Rakyat. Always verify with official government sources.",
    confidence: { high: "High match", medium: "Medium match", low: "Verify this one" },
  },
  zh: {
    kicker: "分享的回答",
    q: "问",
    sources: "来源",
    ask: "提出您自己的问题",
    back: "返回 Lingua Rakyat",
    disclaimer: "此回答由 Lingua Rakyat 生成。请务必以官方政府来源为准核实。",
    confidence: { high: "匹配度高", medium: "匹配度中", low: "请核实" },
  },
}

function copyFor(language?: string) {
  if (language?.startsWith("zh")) return COPY.zh
  if (language?.startsWith("ms") || language?.startsWith("id")) return COPY.ms
  return COPY.en
}

function ConfidenceBadge({
  label,
  text,
}: {
  label: string
  text: string
}) {
  const isHigh = label === "high"
  return (
    <span
      className={
        isHigh
          ? "inline-flex items-center gap-1.5 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold text-primary"
          : "inline-flex items-center gap-1.5 rounded-full border border-warning/40 bg-warning/10 px-3 py-1 text-xs font-semibold text-warning"
      }
    >
      <ShieldCheck className="h-3 w-3" />
      {text}
    </span>
  )
}

function formatDate(iso: string, language?: string) {
  try {
    return new Date(iso).toLocaleDateString(
      language?.startsWith("ms") ? "ms-MY" : language?.startsWith("zh") ? "zh-CN" : "en-US",
      { day: "numeric", month: "short", year: "numeric" }
    )
  } catch {
    return ""
  }
}

export default async function SharePage({ params }: SharePageProps) {
  const { slug } = await params
  const data = await getShare(slug)
  if (!data) notFound()

  const copy = copyFor(data.language)
  const confidenceText =
    copy.confidence[(data.confidence_label as "high" | "medium" | "low") ?? "medium"] ??
    copy.confidence.medium

  return (
    <div className="relative flex h-dvh flex-col overflow-hidden bg-background">
      {/* Same KL-skyline image as the homepage, but pushed further back —
          heavier overlay + blur so it reads as atmosphere behind a focused
          single-answer page rather than a hero illustration competing with it. */}
      <div
        className="fixed inset-0 z-0 bg-cover bg-center bg-no-repeat"
        style={{ backgroundImage: `url(${bgNew.src})` }}
      />
      <div
        className="fixed inset-0 z-0 bg-cover bg-center bg-no-repeat sm:hidden"
        style={{ backgroundImage: `url(${bgMobile.src})` }}
      />
      <div className="absolute inset-0 z-[1] bg-background/70 backdrop-blur-[6px] dark:bg-background/88 dark:backdrop-blur-[8px]" />

      <div className="relative z-10 mx-auto flex h-full w-full max-w-2xl flex-col px-4 py-4 sm:py-8">
        {/* Header — always visible, never scrolls */}
        <div className="mb-3 flex shrink-0 items-center justify-between sm:mb-6">
          <Link href="/" className="flex items-center gap-2.5">
            <Image
              src={logo}
              alt="Lingua Rakyat"
              width={28}
              height={28}
              className="rounded-full object-cover"
            />
            <span className="font-heading text-xs font-semibold tracking-[0.3em] text-foreground uppercase">
              Lingua Rakyat
            </span>
          </Link>
          <Link
            href="/"
            className="hidden items-center gap-1.5 text-xs font-medium text-muted-foreground transition-colors hover:text-primary sm:flex"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            {copy.back}
          </Link>
        </div>

        {/* Receipt card — fills remaining height; only the answer inside scrolls */}
        <div className="relative flex min-h-0 flex-1 flex-col overflow-hidden rounded-[1.75rem] border border-border bg-card/95 shadow-xl backdrop-blur-sm">
          <div className="flex min-h-0 flex-1 flex-col p-5 sm:p-8">
            {/* Eyebrow row: kicker + agency + confidence + date — fixed */}
            <div className="mb-3 flex shrink-0 flex-wrap items-center gap-2 sm:mb-5">
              <span className="text-xs font-semibold tracking-[0.25em] text-primary uppercase">
                {copy.kicker}
              </span>
              {data.agency ? (
                <span className="rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
                  {data.agency}
                </span>
              ) : null}
              {data.confidence_label ? (
                <ConfidenceBadge label={data.confidence_label} text={confidenceText} />
              ) : null}
              {data.created_at ? (
                <span className="ml-auto text-xs text-muted-foreground">
                  {formatDate(data.created_at, data.language)}
                </span>
              ) : null}
            </div>

            {/* Question — matches the homepage's terminal-style Q/A preview — fixed */}
            <div className="mb-3 shrink-0 rounded-xl border border-white/10 bg-[oklch(0.2_0.03_152)] px-4 py-3 font-mono text-sm text-[oklch(0.85_0.02_152)] shadow-sm sm:mb-5 sm:px-5 sm:py-4">
              <span className="font-bold text-[oklch(0.7_0.15_152)]">{copy.q}: </span>
              {data.question}
            </div>

            {/* Scrollable region: answer + sources — everything else stays put */}
            <ScrollArea className="min-h-0 flex-1">
              <div className="pr-3">
                <ChatMarkdown content={data.answer} />

                {data.sources.length > 0 && (
                  <div className="mt-6 border-t border-border pt-4">
                    <div className="mb-2.5 flex items-center gap-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
                      <BookOpen className="h-3.5 w-3.5" />
                      {copy.sources}
                    </div>
                    <div className="flex flex-wrap gap-1.5">
                      {data.sources.map((s, i) => (
                        <span
                          key={i}
                          className="rounded-full border border-border/60 bg-muted/30 px-3 py-1 text-xs text-muted-foreground"
                        >
                          {s.doc_name || s.document_id}
                          {s.page_start ? ` · p.${s.page_start}` : ""}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </ScrollArea>
          </div>

          {/* Torn receipt edge — the one signature flourish, earning its
              keep since this literally is a shareable answer "receipt". */}
          <div
            className="h-4 w-full shrink-0 bg-background"
            style={{
              maskImage:
                "repeating-linear-gradient(90deg, transparent 0 6px, black 6px 16px)",
              WebkitMaskImage:
                "repeating-linear-gradient(90deg, transparent 0 6px, black 6px 16px)",
              maskSize: "16px 100%",
              WebkitMaskSize: "16px 100%",
            }}
          />
        </div>

        {/* CTA + disclaimer — always visible, never scrolls */}
        <div className="shrink-0">
          <Link
            href="/workspace"
            className="group mt-4 flex items-center justify-center gap-2 rounded-full bg-primary px-6 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm transition-all hover:bg-primary/90 hover:shadow-md sm:mt-6 sm:py-3"
          >
            {copy.ask}
            <ArrowRight className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
          </Link>

          <p className="mt-3 text-center text-xs leading-relaxed text-muted-foreground sm:mt-4">
            {copy.disclaimer}
          </p>
        </div>
      </div>
    </div>
  )
}
